version: '3'
services:
  biliup:
    image: ghcr.io/xueba0458/biliup:latest
    container_name: xueba-biliup
    restart: unless-stopped
    ports:
      - "<HOST_ADDRESS>:<HOST_PORT>:19159"
    volumes:
      - /path/to/save_folder:/opt
    command: --password <your_password>
